### PR TITLE
Authconfig, redirection for signin, signup added

### LINKED ISSUE #79: AuthConfig and Authredirect integration for signin flow
Integrate the Authredirect and AuthConfig code and implement signin flow.

### PR DESCRIPTION
**Pull request by kalimuthu-a**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #79 

Test URLs:
- Before: https://main--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity
- After: https://authconfig--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity

### CODE REVIEW

**Review by sselvara — CHANGES_REQUESTED** [review]
@kalimuthu-a  resolve the conflicts in header.js file.

**Comment by kalimuthu-a** [comment]
> @kalimuthu-a resolve the conflicts in header.js file.

This is done @sselvara

**Comment by sselvara** [comment]
@kalimuthu-a  in mobile view profile icon and  signin/signup links in hamburger menu are not clickable, pls fix

**Review by sselvara — APPROVED** [review]

**Comment by kalimuthu-a** [comment]
> @kalimuthu-a in mobile view profile icon and signin/signup links in hamburger menu are not clickable, pls fix

@sselvara  - This is fixed. Pls check

**Review by sselvara — APPROVED** [review]

**Pull request merged**
